### ISSUE TITLE
Needs a LICENCE.md

### ISSUE THREAD

**Issue by yanfali** [awakenetworks/eslint-config-awake#10]
not easy to re-use this without a license file, it'd be great if you could add one @rygine

**Comment by paulyoung** [comment]
@yanfali the `package.json` file says `MIT`, if that's any help.

**Comment by yanfali** [comment]
Thanks. I still think it would be better to have an explicit license, that's sort of a GitHub best practice and is clearer.

**Comment by yanfali** [comment]
https://choosealicense.com/ is githubs own helpful website on the subject with template licenses.

**Comment by rygine** [comment]
open a PR? ;)

**Comment by yanfali** [comment]
Sure.

**Comment by yanfali** [comment]
https://github.com/awakenetworks/eslint-config-awake/pull/11
